import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";

import { ThemeProvider } from "@/providers/theme-provider";
import { Layout } from "@/components/layout";
import { QueryClientProvider } from "@/providers/query-client-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans} ${GeistMono} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
          enableSystem
        >
          <QueryClientProvider>
            <Layout>{children}</Layout>
          </QueryClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
